# Generated by Django 5.1.1 on 2024-09-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(default=1, auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('data', models.DateTimeField()),
                ('local', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=255)),
                ('unidade', models.CharField(max_length=255)),
                ('obs', models.CharField(max_length=255)),
                ('pavimentation', models.CharField(max_length=255)),
                ('eletricity', models.CharField(max_length=255)),
                ('ilumination', models.CharField(max_length=255)),
                ('quantity_houses', models.CharField(max_length=255)),
                ('photos', models.ImageField(upload_to='')),
                ('Reports', models.CharField(max_length=600)),
            ],
        ),
    ]
