# Generated by Django 5.1.1 on 2024-09-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_rename_reports_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='Reports',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='report',
            name='data',
            field=models.DateField(),
        ),
    ]
