# Generated by Django 5.1.1 on 2024-10-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_report_datetime_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='photos',
            field=models.FileField(upload_to='report'),
        ),
    ]
