# Generated by Django 5.1.1 on 2024-10-03 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_report_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='Reports',
            field=models.CharField(blank=True, default='Não há relatórios', max_length=600),
        ),
        migrations.AlterField(
            model_name='report',
            name='data',
            field=models.DateField(default=datetime.date(2024, 10, 3)),
        ),
        migrations.AlterField(
            model_name='report',
            name='photos',
            field=models.ImageField(default='report/404.png', upload_to='report/slogan_images'),
        ),
    ]
