# Generated by Django 5.1.1 on 2024-10-03 14:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_alter_report_reports_alter_report_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
