# Generated by Django 5.1.1 on 2024-09-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_imagem_pageshome_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageshome',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pageshome',
            name='nome',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
