# Generated by Django 5.1.1 on 2024-09-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_pageshome_description_alter_pageshome_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageshome',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
