# Generated by Django 5.1.1 on 2024-09-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_nome_pageshome_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageshome',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
