# Generated by Django 5.1.1 on 2024-10-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_pageshome_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageshome',
            name='link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
